services:
- docker
script:
- export SAVE=$PWD cnt="ubungxctr" slim=".slim"
- docker build -t ubungxctr .
- ./scripts/slimmer.sh
before_deploy:
- cd
- wget `curl -s https://api.github.com/repos/appc/docker2aci/releases | grep browser_download_url
  | head -n 1 | cut -d '"' -f 4` -O d2a.tar.gz
- tar -zxf d2a.tar.gz && rm d2a.tar.gz && d2a=`ls | grep "docker2aci*"` && d2a=`basename
  $d2a` && alias d2a='${PWD}/${d2a}/docker2aci'
- docker save -o ubungxctr.slim.tar ubungxctr.slim
- "${PWD}/${d2a}/docker2aci ubungxctr.slim.tar"
- xz -9 -c ubungxctr.slim.tar > ubungxctr.slim.tar.xz
- docker login -e $QUAYE -u $QUAYL -p $QUAYP  quay.io
- docker tag ${cnt}${slim} quay.io/natostanco/$cnt:$TRAVIS_TAG
- docker push quay.io/natostanco/$cnt:$TRAVIS_TAG
deploy:
  provider: releases
  api_key:
    secure: SDzo9pHowsVMLaYsHHt6g3f1AxI1wWpnrQCh0f+46k3VH5nt44uA4sOUKzOOB66xG0e3y1A+vgkrthnf/+FIwAp5gfuwosR0AuQuBT+82CmKnuyZFQa/wxANGYlt7R9jlAiuf10nahbi/oDI6K+Rv8erVxY92STk0rGzEkqfSBhgQu6TwPRYPMVZ6Lm5gkhbyqIxL4nZttNkE/yj1j+6pmZUpWc0UIH9PRhjOfvVQ9uPabnY5VKfxdNzeIN+DTSMe2wkpzMZ86BqDFzkhxWk2gyVD2PZ3wGGZkss5iUK+uEiEj+dZt2uYxWqD3v9TMrv410PLHTBBqVKTqL0PvPqM7kmIM7ysFTVyfjHF+vMjgHOye9IruVPhUITfhwNwPT9jJzHe6Qzb/m59Bwxc1WZ+nId+ioPiW75D2pHTnMYheLLaXKvSYUpq0k1g0OOMG8yVAHWKt+FrJcDMMVQIMcKlzCcbhPOocmvEB+FlS+vlk/FyU9OOxSJRreY+nAaoTGGwYJ6oStk6m/5G4ONZUGwzIXyaAkkCaO6CR8ZUwzHFCaWjuS+hQ4T2S2Z2Mhy4N8um8jsQSlAyCrOHdv2+Kmx0rFNLv5MTuqaiXLLxnAct7gQfTX4ygIzFPodFzLgb7pHU5i4AmG+YynRarABuNczKZHDqEkOzFXbl6orkE6Nsqk=
  file:
  - ubungxctr.slim.tar.xz
  - ubungxctr.slim-latest.aci
  skip_cleanup: true
  on:
    tags: true
env:
  global:
  - secure: pxXQhXjfwhZeVvatCDoAeaDdDkw2YiJ01sstn3GiiXpPbJQB4bqUStrpaK7hB5Ttg5eHJcyyKA7PS9Xd9VFwb8eIZwx5fCik8vWxDOShw8EHQJIvn287N564s4e3VxYHA5I8ZceMM7bug+l8gWzac5BSzH8S1aUcAMGKpRcbP/ZHX6zMCfEQLt5o/CyPS+Eow2854pacARyHtv2QIdWRlZkPjXkzsuFoHEMHdNGm0XXRrt2yIdMw2NKIGXVYH96B5gskq9DzwOfp0cdsDrBqkveBkti54wbLroXJjUnqttdf+cMAcWYYfwNReEfEet8Ib9oHO9rK0J/HPGnoW8hIbo7DqUAinbwVJJ78fT/FKWpfrl/AZmbKq+4AIo0BYPumGnTR2S163rhKghhbSAfKLPrnPiH4MAHV5ku6JwsV1wb/m8xMQz5h7kQGHETBUmKu8b2r15n6rEynBqpNeu+2bW4Bw8UlN9JdAQHK/JZmNIs1YZ6Tzwl19BlBqtMyEBFUlMvcoD+r//bVgbUHgqk9CsDb2/YikEmomUjFXPy7Js2sV6UUEUjsnTjFF2yCWA7r07nAHZ+snh26mE9l34yIR/icDpWu5+3O9D0e0SVR/hK+9JBL7No3o2f1WLSfGob4klty47SPpCBi+utsfnY5QPNgD1I1Qbzq0GfsvDV7lhg=
  - secure: E/J1DUddpB2NbeQn10Ch1MM5LC2dljtBQPuN70c3aEta4hx/GwkbLxEWYi4IiIWbvVN6+l1lD38tzuv1PTOPydRkUlPpv1shHvCD5YQL3HifwbZFj1Um236ZPVRKwhX0jRzOK7nAOPYNRgkpELRs4oaMpSRMFhA0UjN4OlCbdvm+rFHMcEYD9WVUags7afQEdsrQZSOc0jgoyKakuaDARERao7X0Kvtx8igTMn6EN6PI7J4neijKCAuBkRwPYAxrbSVTUu+u5AFuUj6QqogEOZHVZrgPsrxfpGulscAJRo/lHwqNg7zy7YypqdSKi6THDn+5e9BQ8ufa3z4UOFjg8dxGn1BpDDSmIDP4e1mc3m0Bp66t8l0lkCifRxOjvW1GQhPAKBtcFwzWgj7W9gAddMpcIaDXeUiznTMxx4SaraHPXYljUvyPs8OMmt9hZoyQBue8w3EbJiwt+T7T57KUnYX1i98/1slGegaq/wRrCMvoORY2Rq3QVV8w5EtMjw9vrfik8G5Ev5scYHeUxSF8y4+XsQ5wUXeluNvI7AnVkacTBFufyI7i/vbCvaBnRAdrm5Mw6LIOPlTbzxwQsTy6N9zQh3/kD53Hj4ByKzGZW2NLB+xuNpsEV77IlhfPOq5+Ydqz9sjAO7qdWYpDIoPQHC+rsH0oMW2mRIPWCocHDxM=
  - secure: gkUr45zPS4LsVQHDTcdMy7WQf3rQ11Im16p/L5fJ2kS9UGfwYl2sDXEmw4kiI+FU0jbfWf1X2lhAXAT1IZHn5HmVZszEC7dFKEY5bbAgmpzJbI0m/2wHxbppBC6V7jWLML6/MxKJP+CamzoMCs9KA0Ky4Z3M/jrRsnnvPXnZ7g5t9ycmJwh7jEzEBMh56eBJ24KVl34/B+ECJ8Aa79S3rSNm5IVO9LrBLeGfZ3GVAA1Kuvv7DEMDvx9UStqh1WrNec304qmNoIn+uJw72+7zsfppo2R5/Gzr5sX5EHlCiASOE7GcEEa9G1kuYzZ6FxIit9d04lmxuUWyJqZcruoYo4Y5bZSZdBBdg80gH7mwS/kSI1AffwZ8HqyO+az273t8MO5B5KD/pCwRTD7ssCbj8cheruRHRn1ggbn8r+q66FmDFQdnbTaxFp6s7nb2YmrKuwoLZW/JzsbBTdEKViyAGXwop8yD3ZNZ4AxOB+foD/07wySBFMwxy3f460xqNN8rZ94oPM6nJAF4Zcs3YMIULQJivupIW9iTVmHkHPq7sW0LjoIGdtJd8dg+0J30nT/v2LjxUi9EI8uXB+96fOYAzZjZ19rxHPmKVsjcri8LYNIkqm+4T5r5wh3lquPmVsLBL2WDoymNZ+td2WYs3nAvX9/yekOk0rjt1M4wNvg4tho=
